### ISSUE TITLE
Error loading shared library

### ISSUE THREAD

**Issue by G-Pereira** [zzag/dynamic-wallpaper-importer#4]
I am getting this when I try to run the command:

`dynamic-wallpaper-importer: error while loading shared libraries: libdynamicwallpaperimportercommon.so: cannot open shared object file: No such file or directory`

OS: Fedora 31 KDE

**Comment by G-Pereira** [comment]
Just fixed it by installing `qt5-qtbase-private-devel`

**Comment by zzag** [comment]
It's a bit strange issue because `qt5-qtbase-private-devel` contains things such as private headers that are not particularly required for this tool to work. It would be helpful to have the output of `ldd (which dynamic-wallpaper-importer)`.

**Comment by G-Pereira** [comment]
Probably I did a clean build and that made me think it was the new package that solved the issue. I am not sure now. I think that if the problem is really there someone will come back to this issue (or opens a new one) since Fedora has a reasonable number of users.
