### ISSUE TITLE
Missing importer plugins on manjaro

### ISSUE THREAD

**Issue by szymex73** [zzag/dynamic-wallpaper-importer#5]
Hi,
After installing dynamic-wallpaper-importer from AUR and running the example command I have a following error:
```
No importer plugins have been found
```

I'm running Manjaro with kernel v5.4.23-1-MANJARO

**Comment by szymex73** [comment]
After recompiling the program and a full system update it seems to work

**Comment by zzag** [comment]
> After recompiling the program and a full system update it seems to work

Seems like a Qt version mismatch or something.
